### PR TITLE
fix(tokenizer): Drop chunks after emitting tokens

### LINKED ISSUE #292: Rewriter: text content longer than 65536 chars is truncated
See minimal reproduction here: https://github.com/hedgepigdaniel/parse5-bug

I tried to find a bug in the `parse5-sax-parser` but the test I created for it succeeds: https://github.com/inikulin/parse5/compare/master...hedgepigdaniel:test/waterline?expand=1

So I assume that it has something to do with the `sourceCodeLocationInfo` option passed to the `SAXParser` by `RewritingStream`.

An effective workaround is to set `RewritingStream().tokenizer.preprocessor.bufferWaterline = Infinity` as seen here: https://github.com/hedgepigdaniel/parse5-bug/blob/master/index.js#L7-L8

### PR DESCRIPTION
**Pull request by fb55**
Fixes #292, #357

We would sometimes drop chunks before the corresponding tokens were processed by the rewriting stream. This led to #292. Now, we will drop buffers after emitting events.

BREAKING CHANGE: The SAX parser and rewriting stream will now emit text events when the underlying buffer will be dropped right after the event.

@qnighy I've adopted your test from #357 — hope that's okay! I'd also love it if you could make sure this works for you.

### CODE REVIEW

File: packages/parse5/lib/tokenizer/index.ts [hunk 1]
```diff
@@ -536,6 +542,7 @@ export class Tokenizer {
             if (this.currentCharacterToken.type !== type) {
                 this.currentLocation = this.getCurrentLocation(0);
                 this._emitCurrentCharacterToken(this.currentLocation);
```
Comment (fb55) [inline packages/parse5/lib/tokenizer/index.ts:544]: We can't drop the parsed chunk in `_emitCurrentCharacterToken`, as it is called from `prepareToken` and would remove the token right afterwards.

File: packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts [hunk 2]
```diff
@@ -305,4 +305,48 @@ describe('RewritingStream', () => {
...
+    it.only('Should emit comment after text correctly', (done) => {
+        const source = `${'a'.repeat((1 << 16) - 3)}<!-- foo -->`;
+        const parser = new RewritingStream();
+        let output = '';
+
+        parser.on('data', (data) => {
+            output += data.toString();
+        });
+
+        parser.once('close', () => {
```
Comment (fb55) [inline packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts:340]: Switching this line to the `finish` event will make the test fail, due to the stream buffer waterline being hit. Other tests have been updated to also use the `close` event, for consistency.

**Review by wooorm — COMMENTED** [review]
not my area of expertise in this code base. But if the test was broken before and works now, :+1:

**Comment by qnighy** [comment]
Thanks a lot for the fix!
